api:
  id: "123456" # replace with real id once added to api manager

https:
  basePath: "/v1/*"
  timeouts:
    connection: "30000"
    response: "30000"

reconnection:
  frequency: "500"
  attempts: "3"
